### ISSUE TITLE
PERSONAL TASK: junction transition management

### ISSUE THREAD

**Issue by kianzarrin** [kianzarrin/NodeController#1]
---
TODO list:
- [x] Remember the default state of the node. data should be released when we cycle back to the default state of the node.
- [x] primary click changes node/texture type. secondary click changes offset.
- [x] patch `ReleaseNode` to release data.
- [x] patch `CalculateCorner` 
- [x] serialization.
- [x] Create UI `[xxx---]`
- [x] corner offset should functionally change cars paths.

-stage 2
- [x] UI Node Type Drop Down should not populate unsupported node types
- [x] patch TMPE to setup/disable default crossings.
- [x] patch TMPE to modify entering blocked junction behavior.
- [x] thread safety.

stage 3:
- [x] remove forward flags.
- [x] deal with bend nodes
- [x] support asym road
- [x] refresh node data when segment is upgraded/removed/moved.
- [x] update nodes after load.
- [x] insert node tool.
- [x] render nodes near selected node.
- [x] roads with only one pedestrian lanes cannot be crossings node.
- [x] labels and hints.
- [x] proper UI button.
- [x] test with CSUR
- [x]  force crossing corner offset to zero.

stage 4:
- [x] serialize UI position globally.
- [x] checkbox to remove node markings (only custom)
- [x] new node defaults to crossing (if has pedestrian) or custom (othewise).
- [x] reset to default option.
- [x] if no node is selected left click disables tool.
- [x] only add central crossing texture if both crossings are allowed.
- [x] show TMPE overlay.
- [ ] Tutorial
- [x] Wiki

step 5:
- [x] separate control of corner offset (perhaps in network skins?)
- [X] Move it mod compatibility.
- [ ] corner offset to increase chances of train track connection.
- [x] unflatten junctions
- [x] customize flat junctions, clip segments, end node radius.
- [ ] remove flags by patching `NetLane.RenderInstance()`. see networkskins
- [ ] Handle lod textures.
- [ ] give error if node is expanded too much.
- [ ] set min offset in slider.
- [x] manage traffic light.

Bugs:
- sometimes corner offset causes cars to go on a path different than the one visualized. a base game bug but needs fixing.
- [x] Update Nodes on Load.
- [x] fix support for asym road.
- [x] fix corner offset for trains.
- [x] TMPE overlay UI is confused about the traffic rules. most notability the overlay shows crossing is banned while it is allowed.
- [ ] u-turn node when one segment is oneway enables uturn for both segments.
- [ ] stretch texture for asym roads can be inverted.

CSUR:
- [x] test with CSUR
- [x] update corner offset transpiler.
- [x] find a way to measure CSUR corner offset to use for initialization.

Third-party
- [x] HideCrosswalks does not hide crossings if it is banned by default.
- [x] Move TMPE configurations to TMPE.
- [x] TMPE: option to hide forward flags.
- [x] TMPE: manage path finder priorities (cars are more hesitant go to through junction than middle node). Does TMPE main road priority sign resolve this problem?

rejected:
- [ ] options to remove crossings on transition nodes by default.
- [ ] DIRECT CONNECET: `RenderInstace` patch should use  data matrices from direct connect.

Image blow shows 3 types of transition when two roads are connected:
![Screenshot (310)](https://user-images.githubusercontent.com/26344691/72640938-9c06cb00-3971-11ea-89cf-3ca3ca59c3d8.png)
A.  No transition: this happens when there is equal number of lanes on each of the connected roads
B. Sharp transition: This happens when the number of lanes mismatch but the width of the roads are the same.
C. Gradual transition: This happens when the connected roads have different width.

Perks:
- ~~no transition required when a parking lane transitions into a bus lane. (generally parking/bus/bike lanes do not need to transition into one another).~~ No transition is required between parking and bike lanes
- no transition needed between normal and bus lanes. 
- sharp transition occurs when road half with is the same but there is lane mismatch. this is particularly annoying when you want to remove parking near junctions to make space for dedicated right turn lane.

I think the user should have control over which type of transitional node is used (A B or C).

**Comment by kianzarrin** [comment]
![Screenshot (833)](https://user-images.githubusercontent.com/26344691/79075035-cbbb3a00-7cf8-11ea-9bea-075e63a961b9.png)
Partial success. now have to learn how to deal with matrixes

**Comment by kianzarrin** [comment]
![Screenshot (834)](https://user-images.githubusercontent.com/26344691/79075143-9236fe80-7cf9-11ea-8554-97db7aecb6e0.png)

**Comment by kianzarrin** [comment]
![Screenshot (835)](https://user-images.githubusercontent.com/26344691/79083081-7ef55480-7d34-11ea-932b-70ecc20dc7c3.png)
There are so may combinations here about how the nodes should function like, how long the nodes are and how should it look like. but maybe the latter is more relevant as part of [paint lanes on transitions](https://github.com/kianzarrin/myrepo/issues/3) or [runtime continues junction barier](https://github.com/kianzarrin/myrepo/issues/2)
Stretching the nodes is easier than shortening them. Maybe I should introduce minimum blend length based on difference in road width.

I need to write a table about all combinations:
```
crossings=short length | u turn = medium length
default = middle node -> crossing; U-turn; custom blending length; 
total width matches but pedestrian width does not (default = crossing) -> middle node; u-turn; custom length 
road width has small mismatch (default = crossing) -> u-turn; custom length
road width has big mismatch (default = crossing +u-turn) -> custom length.
```
if TMPE does not hide forward flags then I should. Also I can patch TMPE to control default crossing, traffic lights and u-turns.

**Comment by kianzarrin** [comment]
this is how the textures should look like:
```
middle node => no manipulation needed
crossing/u-turn/custom-length => use segment texture instead of node textures; let hide crossings mod hide crossings
```

**Comment by kianzarrin** [comment]
It would also be good to provide options for asset creators to force middle/bend nodes instead of blend junctions. this way CSUR can activate bend segment and avoid this:
![Screenshot (837)](https://user-images.githubusercontent.com/26344691/79116258-a67a0a80-7d90-11ea-84ba-69b02e9eb1bc.png)

**Comment by kianzarrin** [comment]
TODO list:

- [ ] patch `RenderProps` to remove props lane arrow and street sign props
- [ ] patch `ReleaseNode` to release data.
- [ ] patch `CalculateCorner` (instance member).
- [ ] `RenderInstace` patch should use  data matrices from direct connect.
- [ ] Remember the default state of the node. data should be released when we cycle back to the default state of the node.
- [ ] primary click changes node/texture type. secondary click changes offset.
- [ ] use bend node instead of middle node where necessary.

**Comment by kianzarrin** [comment]
Progress!
[BlendRoadManager.zip](https://github.com/kianzarrin/BlendRoadManager/files/4497404/BlendRoadManager.zip)
Requires: TMPE and Hide Crossings
recommended Elektrix road tools for adding new nods.

![Screenshot (854)](https://user-images.githubusercontent.com/26344691/79668585-01f82e00-81bf-11ea-96a0-ded45d89039f.png)
![Screenshot (852)](https://user-images.githubusercontent.com/26344691/79668630-04f31e80-81bf-11ea-9b45-0168644d0203.png)

**Comment by originalfoo** [comment]
looking good!

**Comment by kianzarrin** [comment]
Updates on my Node/Junction controller Mod
No more forward arrows at road transitions.
![Screenshot (944)](https://user-images.githubusercontent.com/26344691/80570123-eb45a880-8a02-11ea-9af8-9f188f218b38.png)
Multiple ways of handling road transitions:
![Screenshot (945)](https://user-images.githubusercontent.com/26344691/80570112-e84ab800-8a02-11ea-9d95-0468dd5b17f9.png)
There is also basic support for asym road where asym road reverts direction.

**Comment by originalfoo** [comment]
Are middle nodes what RWY (Railway assets) call "nodeless" nodes?

**Comment by originalfoo** [comment]
What happens when there's things like bus lanes, tram tracks or trolley bus catenaries?

**Comment by kianzarrin** [comment]
> Are middle nodes what RWY (Railway assets) call "nodeless" nodes?

Yes

> What happens when there's things like bus lanes, tram tracks or trolley bus catenaries?

It works as usual.

**Comment by kianzarrin** [comment]
Picture album:
![Screenshot (945)](https://user-images.githubusercontent.com/26344691/81001151-fad44f80-8e4f-11ea-89cf-8f50004a0d59.png)
![Untitled2](https://user-images.githubusercontent.com/26344691/81000875-8b5e6000-8e4f-11ea-8a99-8afc4f5a287a.png)
![Screenshot (976)](https://user-images.githubusercontent.com/26344691/81004072-7fc16800-8e54-11ea-8b0e-1c2ab901a27d.png)
![Screenshot (977)](https://user-images.githubusercontent.com/26344691/81004545-3aea0100-8e55-11ea-8444-d0751391d657.png)
