### ISSUE TITLE
Possible conflict mods

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/NodeController#10]
The following mods might conflict or otherwise cause problems (more testing required):

1. [Node Spacer](https://steamcommunity.com/sharedfiles/filedetails/?id=2085018096) - I suspect this is what caused #6 
2. [Tiny Segments](https://steamcommunity.com/sharedfiles/filedetails/?id=1586027591) - for obvious reasons

**Comment by kianzarrin** [comment]
My mod does highlight nearby nodes so people will notice them when adjusting corner offset.
In any case Tiny segments is mainly for decorations and I don't think it has any more problems with my mod that it did not originally have. Am I right?

**Comment by originalfoo** [comment]
I think tiny segments removes min size limit on segment length for all networks, not just fences; eg. it allows very short segment roads too. That being said, Move It mod allows same sort of thing (just post-placement, whereas tiny segments in during-placement).

**Comment by kianzarrin** [comment]
OK.

So as conclusion tiny segments is not a compatibility issue because the problem of small segments already exists with tiny segments with or without my mod.

Also increasing corner offset can lead to very tiny segments ( I should fix that ) so its not like tiny segments is adding any problems.

**Comment by kianzarrin** [comment]
closing this because there is no incompatibility issue. I have added to my todo list to protect against small segments.
