### ISSUE TITLE
Unflatten transition nodes?

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/NodeController#12]
Is there any way to unflatten transition nodes? It makes transitions on a slope look awful unless both adjacent nodes are same height (which also looks aweful in most cases).

Would be huge improvement if there was a way to unflatten transition nodes. Just guessing but might be something to do with `m_flatJunctions`?

**Comment by kianzarrin** [comment]
It has been suggested to be to make flat junctions configurable. 
Also I might try to play with clip segment ends to see if I can gain any advantage

**Comment by kianzarrin** [comment]
![image](https://user-images.githubusercontent.com/26344691/90392513-aa4bcf80-e097-11ea-8889-3eeea554435b.png)
