### ISSUE TITLE
Typos need to be corrected

### ISSUE THREAD

**Issue by gjotten** [kianzarrin/NodeController#21]
@kianzarrin I'm moving into your repo here since I don't want to clog up the discord chat all the time with small stuff.

https://github.com/kianzarrin/NodeController/blob/9e50b2f3ef570e16e27b12c4ed390fa539413a92/NodeController/GUI/Settings.cs#L82

**Comment by gjotten** [comment]
@kianzarrin don't know what my role is on this project but I'm fine with submitting PR's if needed.

**Comment by kianzarrin** [comment]
sorry for the late response. i fixed the typo locally and will upload it. thanks!
