### ISSUE TITLE
Button disappears on maps once Unlock All is used.

### ISSUE THREAD

**Issue by Hyperspeed1313** [kianzarrin/NodeController#23]
With a base Cities Skylines install with no mods except Node Controller and Intersection Marking Tool (and all listed dependencies for the above), the button to open the Node Controller (and the [button to open Intersection Marking Tool](https://github.com/MacSergey/NodeMarkup/issues/142)) disappears. It will not reappear in that map even if Unlock All is disabled later on. 

OS: Windows 10
Node Controller: Version 2.0 [Beta]

Some info that may help identify the source- this behavior also affects the Roundabout Builder.

**Comment by Hyperspeed1313** [comment]
So, up until today this issue was consistent. Now that I've made an issue about it, I can't duplicate the problem on my own system. 
¯\\\_(ツ)\_/¯

**Comment by kianzarrin** [comment]
Button can be covered up with buttons from other mods or if you use advanced toolbar mod. use Control+N hotkey 

ill create a new mod called United UI to deal with those buttons. come to my discord if you like to see pre-release version.

**Comment by Hyperspeed1313** [comment]
A lot of testing later, I figured out this only happens if Unlock All has been used AND [Boogieman Sam's Airport Roads](https://github.com/SamsamTS/CS-AirportRoads/issues/3) is also enabled. It's gotta be something that his mod does that hides the buttons.
