### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by kianzarrin** [kianzarrin/NodeController#4]
Please put your questions, feedback, bug reports in the comments bellow.
You can DRAG AND DROP PICTURE/TEXT FILE

**Comment by DV-13** [comment]
Is it safe to use in an existing heavily modded city? Will it be safe to remove afterwards?

**Comment by kianzarrin** [comment]
its safe to add and remove this mod. at any point.
But once you remove it you will loose all your custom nodes.
This is still pre release testing so do take backup.

**Comment by LemonsterOG** [comment]
**Missing UI Button -- Except in Transport Menu Road Selections**

[CS_PlayerLog_200527_0335.txt]
(https://github.com/kianzarrin/NodeController/files/4687332/CS_PlayerLog_200527_0335.txt)

![NodeController_RegRoad -- UI Button Missing](https://user-images.githubusercontent.com/57635629/82993432-8a43cd00-9fce-11ea-845e-c911e6d695c6.jpg)

![NodeController_RoadBus -- UI Button Missing](https://user-images.githubusercontent.com/57635629/82993438-8c0d9080-9fce-11ea-9738-57af5cf0d565.jpg)

![NodeController_TransBusRoad -- UI Button Visible](https://user-images.githubusercontent.com/57635629/82993446-8dd75400-9fce-11ea-9824-9fb38e6d2944.jpg)

![NodeController_TransTramRoad -- UI Button Visible](https://user-images.githubusercontent.com/57635629/82993452-90d24480-9fce-11ea-9496-3b3f5976d25e.jpg)

**Comment by LemonsterOG** [comment]
**Missing UI Button -- Except in Transport Menu Road Selections**

[CS_PlayerLog_200527_0335.txt]
(https://github.com/kianzarrin/NodeController/files/4687332/CS_PlayerLog_200527_0335.txt)

NodeController_RegRoad -- UI Button Missing
![NodeController_RegRoad -- UI Button Missing](https://user-images.githubusercontent.com/57635629/82993432-8a43cd00-9fce-11ea-845e-c911e6d695c6.jpg)

NodeController_RoadBus -- UI Button Missing
![NodeController_RoadBus -- UI Button Missing](https://user-images.githubusercontent.com/57635629/82993438-8c0d9080-9fce-11ea-9738-57af5cf0d565.jpg)

NodeController_TransBusRoad -- UI Button Visible
![NodeController_TransBusRoad -- UI Button Visible](https://user-images.githubusercontent.com/57635629/82993446-8dd75400-9fce-11ea-9824-9fb38e6d2944.jpg)

NodeController_TransTramRoad -- UI Button Visible
![NodeController_TransTramRoad -- UI Button Visible](https://user-images.githubusercontent.com/57635629/82993452-90d24480-9fce-11ea-9496-3b3f5976d25e.jpg)

**Comment by kianzarrin** [comment]
@LemonsterOG its hiding under the Road button. this is what happens when you use advanced toolbar mod. Just use the configurable shortcut (Control+N).
