### ISSUE TITLE
Array index out of range

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/NodeController#6]
![image](https://user-images.githubusercontent.com/1386719/81763359-eedb3400-94c6-11ea-9b4b-950669ffdb3c.png)

```diff
Simulation error: Array index is out of range.
- at NodeController.Util.NetUtil/<GetLanesCoroutine2>d__47.MoveNext () <0x000c5>
at NodeController.UpdateLanes.AllFlagsAreForward (uint16,NetInfo/Direction) <0x00115>
at NodeController.UpdateLanes.Postfix (RoadBaseAI&,uint16) <0x000a3>
- at (wrapper dynamic-method) RoadBaseAI.DMD<DMD<UpdateLanes_Patch2>?1467986688..UpdateLanes_Patch2> (RoadBaseAI,uint16,NetSegment&,bool) <0x0272c>
at NetSegment.UpdateLanes (uint16,bool) <0x00092>
- at (wrapper dynamic-method) NetManager.DMD<DMD<SimulationStepImpl_Patch0>?-2106002304..SimulationStepImpl_Patch0> (NetManager,int) <0x00304>
at SimulationManagerBase`2.SimulationStep (int) <0x0004c>
at NetManager.ISimulationManager.SimulationStep (int) <0x00024>
at SimulationManager.SimulationStep () <0x00693>
at SimulationManager.SimulationThread () <0x0018a>
  [Core]
```

A feast of logs...

[AutoRepair.log](https://github.com/kianzarrin/NodeController/files/4619418/AutoRepair.log)

[DuplicateAssemblyScanner.log](https://github.com/kianzarrin/NodeController/files/4619419/DuplicateAssemblyScanner.log)

[HideUnconnectedTracks.debug.log](https://github.com/kianzarrin/NodeController/files/4619433/HideUnconnectedTracks.debug.log)

[NodeController.log](https://github.com/kianzarrin/NodeController/files/4619422/NodeController.log)

[output_log.txt](https://github.com/kianzarrin/NodeController/files/4619428/output_log.txt)

[RMCrosswalks.debug.log](https://github.com/kianzarrin/NodeController/files/4619430/RMCrosswalks.debug.log)

[TMPE.log](https://github.com/kianzarrin/NodeController/files/4619431/TMPE.log)

Also, something wrong with the xml file:

![image](https://user-images.githubusercontent.com/1386719/81763492-4c6f8080-94c7-11ea-8206-6977cd91c9d6.png)

[NodeControllerXML.zip](https://github.com/kianzarrin/NodeController/files/4619427/NodeControllerXML.zip)

**Comment by originalfoo** [comment]
BTW, for some reason node controller button does not appear when I open roads menu. Maybe the broken xml? Or maybe it positions based on UI component I hid using Hide It mod?

I'm using local build of TM:PE 11.5.0.

**Comment by kianzarrin** [comment]
I think I fixed that problem. but haven't uploaded it into steam yet.

**Comment by kianzarrin** [comment]
the xml file is not in xml format! its in binary format.
EDIT: maybe I should just call it config or save or change format? I have higher priority things to consider though.

**Comment by originalfoo** [comment]
It's possibly the reset button that causes error; I'd used that last time, but just happened again and only thing I'd done was increase a node and then reset it.

[NodeController.log](https://github.com/kianzarrin/NodeController/files/4626309/NodeController.log)
[output_log.txt](https://github.com/kianzarrin/NodeController/files/4626311/output_log.txt)
[TMPE.log](https://github.com/kianzarrin/NodeController/files/4626314/TMPE.log)

**Comment by kianzarrin** [comment]
That array index out of range only happens when I want to remove forward flags. wait until I upload the next version or use the master branch build to test this.

**Comment by kianzarrin** [comment]
Actually its preferable to use the master branch rather than subscribing to the asset. I put the asset there for people who could not be bothered to build.

**Comment by kianzarrin** [comment]
I uploaded a fix. But I don't understand why it happens in the first place. How can you get more lanes than there is in NetInfo.m_lanes. Something is fishy here that probably influences TMPE. 
```
            for (uint laneID = segmentId.ToSegment().m_lanes;
                laneID != 0 // && idx < n; // if I comment out this code, the exception would be resolved.
                laneID = laneID.ToLane().m_nextLane, idx++)
```
I will write a test code and ask people to give me log result.

**Comment by kianzarrin** [comment]
@aubergine10
If you saw a file called NodeController.Strange.log can you please send it to me?

**Comment by originalfoo** [comment]
> How can you get more lanes than there is in NetInfo.m_lanes.

Not sure in my current city as I'm only just starting building it - there are no vehicles or houses even, just miles of train track and a road I'm weaving through the mountains heh.

However, I did notice that lanes can be added to segments at run time. How? As far as I can tell things like transport lines! It seems when you route a bus, for example, the bus route is somehow added as lanes. At least as far as I could tell - I didn't investigate fully, as I was looking for somthing else at the time (https://github.com/CitiesSkylinesMods/TMPE/issues/515) and just noticed the weird disconnect between the netinfo and the stuff on the segment. I thought it weird that the segment contained details about the lanes, per segment. Anyway, that's vague recolleciton heh.

But in my current city I have no idea why any extra lanes would be added - I have no transport lines, no cims, no vehicles, etc.

**Comment by originalfoo** [comment]
> If you saw a file called NodeController.Strange.log can you please send it to me?

Can't find that file, but will send it over if it appears.

**Comment by kianzarrin** [comment]
> Can't find that file, but will send it over if it appears.

The file will appear when instead of the array index out of range error on screen.

> I did notice that lanes can be added to segments at run time. 

I really hope the extra lanes are added to the end. because otherwise TMPE is getting wrong lane info from the lanes in rare occasions.

**Comment by originalfoo** [comment]
I assume they get added to the end. Can't remember where I saw it, but analyzing from this should help track it down:

![image](https://user-images.githubusercontent.com/1386719/81970864-17267800-9618-11ea-9259-d12660cdead8.png)

**Comment by originalfoo** [comment]
I'm no longer getting any errors in-game, but there's some stuff in the log file.

[NodeController.log](https://github.com/kianzarrin/NodeController/files/4639470/NodeController.log)

**Comment by kianzarrin** [comment]
You are not getting the NodeController.Strange.log which means one of the following must be wrong:
- you have bus routes
- you created/updated custom transitional node that has a bus route going through it,
- bus routes add extra lanes to the segment.

EDIT: I do have stack trace in the log but that is different than error as you might have guessed already. This is pre-release testing so I am dumping a lot of info in the log. People with different mods are going to have different stack trace and that is going to help me debug some of the problems and save me some time.

**Comment by kianzarrin** [comment]
I tested segment with bus lane it does not have extra nodes. I still don't understand why segments could have extra lanes which is unsettling. If the NodeController.Strange.log  appeared at any moment please send it to me.

**Comment by originalfoo** [comment]
I don't have any transport routes at all.
