### ISSUE TITLE
Suggestion: Different circle color for segments/nodes/junctions

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/NodeController#7]
Currently I always get the yellow circle when dragging over node/junction/segment.

Would be nice to have some color changes:

* Yellow = over segment; clicking will create new crossing node
* Blue = over existing junction node (3+ segments connected to node)
* Green = over some other node (2 segments connected to node)
* Red (already have this) = unable to use at current location (eg. too close to junction)

**Comment by kianzarrin** [comment]
yellow overlay + tiny aesthetic circle is becoming my theme. I think its better to do it with mouse cursor:
- zebra crossing/new node : cursor=zebra
- new node highway: cursor=middle node
- junction: cursor=junction
- other node: cursor=road transition.

Chameleon gave me a bunch of Icon so Id like to put them to some use.

![](https://cdn.discordapp.com/attachments/702171084300091534/708639190488973332/sprites_12.png)
![](https://cdn.discordapp.com/attachments/702171084300091534/708639199674368050/sprites_1.png)
![](https://cdn.discordapp.com/attachments/702171084300091534/708639202560180264/sprites_2.png)
![](https://cdn.discordapp.com/attachments/702171084300091534/708639204938350642/sprites_3.png)
![](https://cdn.discordapp.com/attachments/702171084300091534/708639206804553738/sprites_4.png)
![](https://cdn.discordapp.com/attachments/702171084300091534/708639207991672862/sprites_5.png)
![](https://cdn.discordapp.com/attachments/702171084300091534/708639209639903253/sprites_6.png)
![](https://cdn.discordapp.com/attachments/702171084300091534/708639210461986816/sprites_7.png)
![](https://cdn.discordapp.com/attachments/702171084300091534/708639213360250930/sprites_9.png)
![](https://cdn.discordapp.com/attachments/702171084300091534/708639211699306526/sprites_8.png)

**Comment by originalfoo** [comment]
The cursors will certainly help, but I still think the key visual indicator for most users will be the color of the circle.

The big highlight circle on the road is much more attention-grabbing than small mouse cursor.

**Comment by kianzarrin** [comment]
Green: when inserting new node - Nearby middle nodes maybe moved because I indirectly call `NetTool.SplitSegment()`. This happens in the same way when you attach a new segment near a middle node. Also it resize nearby segments too
Yellow: when modifying existing node.
Red: in case of error/invalid

Alt+Click: to remove existing middle/custom nodes.
Control+Click to insert new middle node without moving nearby nodes.
Click to move nearby middle nodes. For curved roads I can also warn about buildings that are destroyed in the process by highlighting them as orange (https://github.com/bernardd/Crossings/issues/1)

**Comment by originalfoo** [comment]
When a click will insert a crossing, what about having a white 'lane highlight' style shape that crosses the road where the crossing will go? Visually it will serve two purposes:

* Conveys to user a click at that point will insert a crossing (because it somewhat looks like one)
* Looks a bit like a "cut" across the road, hinting that the segment will be split in to two pieces

**Comment by kianzarrin** [comment]
chamelon should I put green for new node?
![image](https://user-images.githubusercontent.com/26344691/90393685-eaac4d00-e099-11ea-83fa-0586c5a56d1d.png)
taggin @aubergine10

**Comment by chameleon-tbn** [comment]
You want to have that red circle as your brandmark if i remember right... :) I can create all cursors with any kind of border color and i already have created red, grey and green borders for the cursors... but on general i would say change the color of the circle in same way the color of the cursor change....

**Comment by kianzarrin** [comment]
@thebugfixnet I forgot to remove that red circle.
But what about the color of the overlay. should it be :
- green stripe when adding a node
- yellow circle/sausage when modifying node/segmentEnd.
- white when node/segment end is selected
- red stripe/circle/sousage in case of failure.

**Comment by chameleon-tbn** [comment]
Sounds good for me - but make the white please not too bright

**Comment by kianzarrin** [comment]
this is fixed
