### ISSUE TITLE
Suggestion: Integrate with Fine Road Tool UI

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/NodeController#9]
If [Fine Road Tool](https://steamcommunity.com/sharedfiles/filedetails/?id=1844442251) is enabled, it would be nice if the button could be put in its UI rather than the main tool strip.

This button opens the UI:

![image](https://user-images.githubusercontent.com/1386719/81771076-f48e4500-94d9-11ea-836f-cfe6967631e1.png)

Which looks like this:

![image](https://user-images.githubusercontent.com/1386719/81771092-fce68000-94d9-11ea-8873-0841d41d4556.png)

[Fine Road Anarchy](https://steamcommunity.com/sharedfiles/filedetails/?id=1844440354) adds it's buttons to that UI, as does the [Node Spacer](https://steamcommunity.com/sharedfiles/filedetails/?id=2085018096) mod.

**Comment by kianzarrin** [comment]
I was hoping to create put all the UI of several mods into a new panel of my own. Maybe I can put all of the mod buttons in the road options in fine road tool.

Or should fine road tool be a place holder for all other UI?

BTW I have fined a way to autosize panel. I just copy pasted code from the private `AutoArrange()` method.

**Comment by s2500111** [comment]
I'd argue against this, as the fine road tools are affecting roads while you build them and this tool is altering them afterwards. I'd even argue for creating a button outside of the road building menu, as accidentally clicking out of the tool and unwantedly upgrading a road is quite a frustrating experience.

But maybe you can copy the style of the FRT-menu, as it looks quite neat.

**Comment by kianzarrin** [comment]
UnifiedUI mod has fixed this
